#!/usr/bin/env bash
#
# start.sh
#
# Builds the forescout-lookup image and runs it as a container that
# restarts automatically (--restart unless-stopped), same pattern as
# fruit-machine/start.sh on this same host. Different ports (8890) so
# it runs alongside the fruit machine without clashing.
#
# The restricted SSH private key (webapp_query_rsa) is NOT baked into
# the image -- it's expected to already exist at ./keys/webapp_query_rsa
# next to this script (bind-mounted read-only, not a named volume,
# since the key is provisioned once by hand, not generated by the app).
#
# Usage: ./start.sh

set -euo pipefail

IMAGE_NAME="forescout-lookup"
CONTAINER_NAME="forescout-lookup"
HTTP_PORT=8890

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEY_DIR="${DIR}/keys"
KEY_FILE="${KEY_DIR}/webapp_query_rsa"
# Scheduled-debug job store -- read-write, unlike keys/ (no secret to
# provision by hand, just an empty writable dir the app persists to).
DATA_DIR="${DIR}/data"
mkdir -p "$DATA_DIR"

if ! command -v docker >/dev/null 2>&1; then
    echo "Error: docker is not installed." >&2
    exit 1
fi

if [[ ! -f "$KEY_FILE" ]]; then
    echo "Error: restricted SSH key not found at ${KEY_FILE}" >&2
    echo "Place the webapp_query_rsa private key there before starting -- it is" >&2
    echo "already trusted on the EM (192.168.22.210) via the forced-command entry" >&2
    echo "added for this app; it is not generated or regenerated by this script." >&2
    exit 1
fi
chmod 600 "$KEY_FILE"

echo "Building image ${IMAGE_NAME} ..."
docker build -t "$IMAGE_NAME" "$DIR"

if docker ps -a --format '{{.Names}}' | grep -qx "$CONTAINER_NAME"; then
    echo "Removing existing ${CONTAINER_NAME} container ..."
    docker rm -f "$CONTAINER_NAME" >/dev/null
fi

echo "Starting container ${CONTAINER_NAME} on port ${HTTP_PORT} ..."
docker run -d \
    --name "$CONTAINER_NAME" \
    --restart unless-stopped \
    -p "${HTTP_PORT}:5000" \
    -v "${KEY_DIR}:/keys:ro" \
    -v "${DATA_DIR}:/data" \
    "$IMAGE_NAME"

echo "Done. Forescout lookup running at http://<host>:${HTTP_PORT}/"
